version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: carbon-components:master    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
label: ":arrow_heading_down: pull"  # Optional
